//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameChest.Resources;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Language {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Language() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameChest.Resources.Language", typeof(Language).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    internal static string SettingsWindowAllowCloseWithEscape {
        get {
            return ResourceManager.GetString("SettingsWindowAllowCloseWithEscape", resourceCulture);
        }
    }

    internal static string SettingsWindowAllowMovement {
        get {
            return ResourceManager.GetString("SettingsWindowAllowMovement", resourceCulture);
        }
    }
    internal static string SettingsWindowAllowResize {
        get {
            return ResourceManager.GetString("SettingsWindowAllowResize", resourceCulture);
        }
    }

    internal static string SettingsWindowOpenLogin {
        get {
            return ResourceManager.GetString("SettingsWindowOpenLogin", resourceCulture);
        }
    }
    internal static string SettingsWindowOpenOnStartup {
        get {
            return ResourceManager.GetString("SettingsWindowOpenOnStartup", resourceCulture);
        }
    }

    internal static string SettingsWindowShowConfigButton {
        get {
            return ResourceManager.GetString("SettingsWindowShowConfigButton", resourceCulture);
        }
    }

    internal static string SettingsTitle {
        get {
            return ResourceManager.GetString("SettingsTitle", resourceCulture);
        }
    }

    internal static string SearchInputLabel {
        get {
            return ResourceManager.GetString("SearchInputLabel", resourceCulture);
        }
    }

    internal static string SettingsGeneralTab {
        get {
            return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
        }
    }

    internal static string OpenPluginFolder {
        get {
            return ResourceManager.GetString("OpenPluginFolder", resourceCulture);
        }
    }

    internal static string OpenPluginConfigFile {
        get {
            return ResourceManager.GetString("OpenPluginConfigFile", resourceCulture);
        }
    }

    internal static string ConfirmationInstructionTooltip {
        get {
            return ResourceManager.GetString("ConfirmationInstructionTooltip", resourceCulture);
        }
    }

    internal static string NewGame {
        get {
            return ResourceManager.GetString("NewGame", resourceCulture);
        }
    }

    internal static string StartGame {
        get {
            return ResourceManager.GetString("StartGame", resourceCulture);
        }
    }

    internal static string StopGame {
        get {
            return ResourceManager.GetString("StopGame", resourceCulture);
        }
    }

    internal static string GameHistory {
        get {
            return ResourceManager.GetString("GameHistory", resourceCulture);
        }
    }
    internal static string GamePhrases {
        get {
            return ResourceManager.GetString("GamePhrases", resourceCulture);
        }
    }

    internal static string StartTimer {
        get {
            return ResourceManager.GetString("StartTimer", resourceCulture);
        }
    }

    internal static string BlockList {
        get {
            return ResourceManager.GetString("BlockList", resourceCulture);
        }
    }
}

