using System.Collections.Generic;

namespace GameChest;

public static class FightGamePhraseCategories {
    public const string RegistrationStart = "RegistrationStart";
    public const string RegistrationEntry = "RegistrationEntry";
    public const string RegistrationReminder = "RegistrationReminder";
    public const string RegistrationOneSlot = "RegistrationOneSlotLeft";
    public const string RegistrationFull = "RegistrationFull";
    public const string FightStart = "FightStart";
    public const string InitiativeResult = "InitiativeResult";
    public const string InitiativeTie = "InitiativeTie";
    public const string Attack = "Attack";
    public const string CriticalHit = "CriticalHit";
    public const string Fumble = "Fumble";
    public const string FightEnd = "FightEnd";
    public const string FightCanceled = "FightCanceled";
    public const string NearDeath = "NearDeath";
    public const string MinionSummon = "MinionSummon";

    public static readonly IReadOnlyList<PhraseCategoryMeta> All = new List<PhraseCategoryMeta> {
        new(RegistrationStart, "Registration Open", new[] { "{max}", "{hp}" }, new[] {
            "The registration period for today's duel is now open!",
            "The Lalarena opens for challengers! Registration is now underway!",
            "The gates to the Lalarena are open. Step forward and declare yourselves!",
            "Registration begins now. The Lalarena awaits its fighters!",
            "The call goes out across the arena-registration is open!",
            "The Lalarena stands ready. Enter now if you dare!",
            "The crowd gathers as registration for today's duel begins!",
            "The fight list is empty no longer-registration is now open!",
            "Warriors, step forward! Registration has begun!",
            "The Lalarena opens its doors for a new clash!",
            "A new duel approaches. Registration is now underway!",
            "The game master calls for contenders. Registration is open!",
        }),
        new(RegistrationEntry, "Fighter Registered", new[] { "{player}", "{playerA}", "{playerB}" }, new[] {
            "{player} enters the Lalarena! Who's going to challenge this mighty opponent!?",
            "{player} steps into the Lalarena with fire in their eyes!",
            "A new challenger arrives! {player} has entered the Lalarena!",
            "{player} answers the call and claims a place in the Lalarena!",
            "The crowd stirs as {player} enters the Lalarena!",
            "{player} storms into the Lalarena and awaits a worthy rival!",
            "{player} has thrown their name into the fight!",
            "The gates open-{player} enters the Lalarena!",
            "{player} is in! Who dares stand against them?",
            "{player} joins the fray and the Lalarena grows louder!",
            "{player} has arrived! The hunt for an opponent begins!",
            "{player} takes the stage in the Lalarena!",
        }),
        new(RegistrationReminder, "Registration Reminder", System.Array.Empty<string>(), new[] {
            "Registration remains open! Step into the Lalarena if you dare!",
            "The crowd grows restless-who will answer the call and enter the Lalarena?",
            "A duel awaits. Registration is still open!",
            "The Lalarena is ready, but the challengers are not yet complete!",
            "Who will be first to claim a place in the Lalarena?",
            "The game master waits. Registration remains open!",
            "The arena stands silent. Who will break it with their name?",
            "The crowd calls for combatants-registration is still underway!",
            "One battle, two fighters. Registration remains open!",
            "Enter the Lalarena and stake your claim!",
            "The challenge has been issued. Registration is still open!",
            "The gates remain open for any who would fight!",
        }),
        new(RegistrationOneSlot, "One Slot Left", new[] { "{playerA}" }, new[] {
            "One slot remains in the Lalarena! Who will step forward?",
            "A single challenger is still needed before the match can begin!",
            "The Lalarena awaits one more brave soul!",
            "One fighter stands ready-who will claim the final spot?",
            "Only one opening remains! Enter now if you dare!",
            "The crowd demands a second contender! One slot is still open!",
            "The Lalarena is nearly set, but one challenger is missing!",
            "One place remains in the ring! Will anyone answer the call?",
            "The first fighter is ready. One more is needed before the clash begins!",
            "A lone warrior waits in the Lalarena for a worthy rival!",
            "One final participant is needed to awaken the Lalarena!",
            "The second slot is still open! Step in and fight!",
        }),
        new(RegistrationFull, "Registration Full", new[] { "{playerA}", "{playerB}" }, new[] {
            "The Lalarena is set! {playerA} versus {playerB}!",
            "Both fighters have entered the Lalarena! Prepare for {playerA} versus {playerB}!",
            "The match is made-{playerA} will battle {playerB}!",
            "The ring is full! {playerA} will face {playerB}!",
            "Two enter the Lalarena: {playerA} and {playerB}!",
            "The crowd erupts! {playerA} and {playerB} are locked in for the fight!",
            "The contestants are ready: {playerA} versus {playerB}!",
            "At last, the Lalarena is complete! {playerA} meets {playerB}!",
            "Both slots are filled! Prepare for {playerA} versus {playerB}!",
            "The arena doors close behind them: {playerA} and {playerB} are in!",
            "The match is set-{playerA} and {playerB} stand ready!",
            "The Lalarena welcomes its final pair: {playerA} and {playerB}!",
        }),
        new(FightStart, "Fight Start", new[] { "{playerA}", "{playerB}", "{max}" }, new[] {
            "{playerA} and {playerB}, roll for initiative with /random {max}.",
            "The duel begins: {playerA} against {playerB}. Roll for initiative with /random {max}.",
            "Fight Club opens with {playerA} versus {playerB}. Roll for initiative with /random {max}.",
            "{playerA} and {playerB} circle one another. Roll for initiative with /random {max}.",
            "The crowd leans in as {playerA} faces {playerB}. Roll for initiative with /random {max}.",
            "{playerA} cracks their knuckles. {playerB} answers in kind. Roll for initiative with /random {max}.",
            "{playerA} and {playerB} step into the ring. Roll for initiative with /random {max}.",
            "Steel nerves, sharp eyes: {playerA} meets {playerB}. Roll for initiative with /random {max}.",
            "All bets are off. {playerA} faces {playerB}. Roll for initiative with /random {max}.",
            "{playerA} squares up with {playerB}. Roll for initiative with /random {max}.",
            "The bell rings for {playerA} and {playerB}. Roll for initiative with /random {max}.",
            "A hush falls over the arena: {playerA} versus {playerB}. Roll for initiative with /random {max}.",
        }),
        new(InitiativeResult, "Initiative Result", new[] { "{attacker}", "{defender}", "{rollA}", "{rollB}", "{max}" }, new[] {
            "{attacker} wins initiative with {rollA} to {rollB} and takes the first move.",
            "{attacker} is quicker on the draw and opens the fight.",
            "{attacker} seizes the initiative and acts first.",
            "{attacker} beats {defender} on the draw and takes control.",
            "{attacker} snatches the first turn away from {defender}.",
            "{attacker} comes out faster and strikes first.",
            "{attacker} takes the tempo early and claims the opening turn.",
            "{attacker} wins the initiative exchange and steps in first.",
            "{attacker} out-rolls {defender} and controls the opening.",
            "{attacker} wins the first heartbeat of the duel.",
            "{attacker} gets the first clear shot at {defender}.",
            "{attacker} takes the lead in the opening exchange.",
        }),
        new(InitiativeTie, "Initiative Tie", new[] { "{rollA}", "{rollB}", "{playerA}", "{playerB}", "{max}" }, new[] {
            "Dead even at {rollA}. Both fighters roll again with /random {max}.",
            "Neither fighter blinks; the initiative is tied at {rollA}. Both fighters roll again with /random {max}.",
            "A perfect tie at {rollA}. Both fighters roll again with /random {max}.",
            "The opening clash is even at {rollA}. Both fighters roll again with /random {max}.",
            "{playerA} and {playerB} match each other at {rollA}. Both fighters roll again with /random {max}.",
            "Too close to call; both fighters rolled {rollA}. Both fighters roll again with /random {max}.",
            "The crowd groans at a tie: {rollA} to {rollA}. Both fighters roll again with /random {max}.",
            "No advantage gained. Initiative is tied at {rollA}. Both fighters roll again with /random {max}.",
            "Neither side takes it; tied at {rollA}. Both fighters roll again with /random {max}.",
            "The first contest ends even at {rollA}. Both fighters roll again with /random {max}.",
            "They move as one and tie at {rollA}. Both fighters roll again with /random {max}.",
            "The opening beat lands in perfect sync at {rollA}. Both fighters roll again with /random {max}.",
        }),
        new(Attack, "Attack", new[] { "{attacker}", "{defender}", "{damage}", "{health}", "{attackerHealth}", "{defenderHealth}", "{max}" }, new[] {
            "{attacker} drives a hit into {defender} for {damage} damage. {defender} has {health} HP left.",
            "{attacker} lands cleanly for {damage} damage. {defender} drops to {health} HP.",
            "{attacker} connects and deals {damage} damage to {defender}. {health} HP remain.",
            "{defender} absorbs {damage} damage from {attacker}. {defenderHealth} HP remain.",
            "{attacker} clips {defender} for {damage} damage. {defender} is down to {health} HP.",
            "{attacker} slips past the guard and deals {damage} damage. {defender} has {health} HP remaining.",
            "{attacker} scores with a solid strike for {damage} damage. {defender} falls to {health} HP.",
            "{attacker} breaks through and hits for {damage} damage. {defender} is left with {health} HP.",
            "{attacker} punishes {defender} for {damage} damage. {defender} now has {health} HP.",
            "{attacker} finds an opening and deals {damage} damage. {defender} remains on {health} HP.",
            "{attacker} swings true for {damage} damage. {defender} is reduced to {health} HP.",
            "{attacker} lands a measured blow for {damage} damage. {defender} clings to {health} HP.",
        }),
        new(CriticalHit, "Critical Hit", new[] { "{attacker}", "{defender}", "{damage}", "{bonus}", "{health}", "{attackerHealth}", "{defenderHealth}", "{max}" }, new[] {
            "{attacker} lands a crushing critical for {damage} damage total, including a {bonus} bonus. {defender} drops to {health} HP.",
            "Critical hit! {attacker} tears through {defender} for {damage} damage with a bonus of {bonus}. {health} HP remain.",
            "{attacker} finds the perfect opening and critically strikes for {damage} damage. {defender} falls to {health} HP.",
            "{attacker} explodes forward with a critical blow for {damage} damage. {defender} now has {health} HP.",
            "A brutal critical from {attacker} deals {damage} damage total. {defender} is left on {health} HP.",
            "{attacker} spikes the damage with a critical hit: {damage} damage total, bonus {bonus}. {defender} falls to {health} HP.",
            "{attacker} lands a devastating crit for {damage} damage. {defender} reels at {health} HP.",
            "Critical strike by {attacker}! {damage} damage total leaves {defender} at {health} HP.",
            "{attacker} turns a perfect roll into {damage} damage total. {defender} is cut down to {health} HP.",
            "{attacker} hammers home a critical for {damage} damage. {defender} has only {health} HP remaining.",
            "{attacker} cashes in the max roll for a critical {damage} damage. {defender} sinks to {health} HP.",
            "{attacker} unleashes a critical burst for {damage} damage, bonus included. {defender} sits at {health} HP.",
        }),
        new(Fumble, "Fumble", new[] { "{attacker}", "{defender}", "{attackerHealth}", "{defenderHealth}" }, new[] {
            "{attacker} fumbles the exchange and loses the next turn.",
            "{attacker} overcommits, stumbles, and will lose the next turn.",
            "{attacker} slips badly and forfeits the next turn.",
            "{attacker} blows the attempt and is stunned out of the next turn.",
            "{attacker} makes a disastrous misplay and loses the next turn.",
            "{attacker} loses footing at the worst possible moment and will skip the next turn.",
            "{attacker} swings wild, misses everything, and loses the next turn.",
            "{attacker} fumbles hard and leaves an opening by losing the next turn.",
            "{attacker} misreads the moment and gives away the next turn.",
            "{attacker} crashes into a mistake and forfeits the next turn.",
            "{attacker} botches the move and must surrender the next turn.",
            "{attacker} falters and pays for it by losing the next turn.",
        }),
        new(FightEnd, "Fight End", new[] { "{winner}", "{loser}", "{attackerHealth}", "{defenderHealth}" }, new[] {
            "{winner} defeats {loser} and stands alone at the end of the duel.",
            "{winner} finishes the fight and drops {loser}.",
            "{winner} claims victory over {loser}.",
            "{winner} wins the duel. {loser} is finished.",
            "{winner} puts {loser} away and takes the match.",
            "The fight is over: {winner} defeats {loser}.",
            "{winner} overwhelms {loser} and closes the bout.",
            "{winner} is the last fighter standing. {loser} falls.",
            "{winner} ends it cleanly and claims the win over {loser}.",
            "{winner} secures the knockout and defeats {loser}.",
            "{winner} takes the fight from {loser}.",
            "{winner} leaves no doubt and defeats {loser}.",
        }),
        new(FightCanceled, "Fight Canceled", new[] { "{playerA}", "{playerB}" }, new[] {
            "The duel has been called off by the game master.",
            "The fight is canceled. Return to your corners.",
            "The game master waves it off. This duel is over before it begins.",
            "The crowd groans as the match is canceled.",
            "The Lalarena falls quiet. This fight has been canceled.",
            "No contest! The game master has ended the fight.",
            "The duel is off. Await further instruction from the game master.",
            "The match has been canceled by official ruling.",
            "The game master ends the bout before another blow is thrown.",
            "This fight is canceled. Stand down, fighters.",
            "The Lalarena doors close. The fight has been canceled.",
            "The game master has canceled the duel. Better luck next time.",
        }),
        new(NearDeath, "Near Death", new[] { "{player}", "{attacker}", "{defender}", "{health}" }, new[] {
            "{player} is near death! Will they survive the fight?",
            "{player} staggers on the brink of collapse!",
            "The crowd gasps-{player} is barely standing!",
            "One more clean hit could finish {player}!",
            "{player} is hanging on by a thread!",
            "The Lalarena senses blood in the water-{player} is in danger!",
            "{player} wavers but refuses to fall!",
            "{player} looks one strike away from disaster!",
            "The crowd can feel it-{player} is almost done!",
            "{player} barely remains standing after that blow!",
            "{player} reels and looks near the end!",
            "{player} is deep in danger now!",
        }),
        new(MinionSummon, "Minion Summon", new[] { "{player}", "{cost}", "{mp}", "{maxMp}" }, new[] {
            "{player} summons a minion and spends {cost} MP. {mp}/{maxMp} MP remain.",
            "{player} calls forth a minion! {cost} MP are consumed, leaving {mp}/{maxMp} MP.",
            "A minion answers {player}'s call. {player} loses {cost} MP and now has {mp}/{maxMp} MP.",
            "{player} brings a minion into the fray! {cost} MP spent, {mp}/{maxMp} MP left.",
            "{player} changes the tide with a summoned minion. {cost} MP are gone; {mp}/{maxMp} MP remain.",
            "{player} unleashes a minion and pays {cost} MP for the privilege. {mp}/{maxMp} MP remain.",
            "{player}'s minion joins the fight! {cost} MP spent, {mp}/{maxMp} MP remain.",
            "{player} calls in backup from beyond. {cost} MP spent; {mp}/{maxMp} MP left.",
            "{player} whistles up a minion and burns {cost} MP. Current MP: {mp}/{maxMp}.",
            "The crowd roars as {player} summons a minion! {cost} MP consumed, {mp}/{maxMp} MP remain.",
            "{player} swaps in a minion and pays {cost} MP. {mp}/{maxMp} MP remain.",
            "{player} empowers the battlefield with a minion summon. {cost} MP spent; {mp}/{maxMp} MP remain.",
        }),
    };
}
